version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
  test:
    steps:
      - run: echo "sample"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

