version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
  test:
    machine: true
    steps:
      - run: echo "sample"
  test2:
    docker: 
      - image: circleci/node:8
    steps:
      - run: npm install
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - test2

